version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/tsatke/verbose-broccoli"

[[analyzers]]
name = "test-coverage"
enabled = true

[[transformers]]
name = "gofmt"
enabled = true
